server:
  context-path: /cowboy
  port: 9999
# profile active config
spring:
  profiles:
    active: dev
  cache:
    ehcache:
      config: classpath: ehcache.xml
#--mybatis config---------------------------
###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.cowboy.*.entity
  #global-config:
    #id-type: 1   #<!-- 全局ID类型： 0, "数据库ID自增"， 1, "用户输入ID", 2, "全局唯一ID", 3, "全局唯一ID"-->
    #db-column-underline: false
    #refresh-mapper: true
    #is-capital-mode: false
  #configuration:
   # map-underscore-to-camel-case: true
    #cache-enabled: true #配置的缓存的全局开关
    #lazyLoadingEnabled: true #延时加载的开关
    #jdbcTypeForNull: NULL
    #multipleResultSetsEnabled: true
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:logback.xml